import React, { useState, useEffect } from "react";
import { Sparkles, Check, X, ShieldAlert, FileText, UserCheck, RefreshCw, CheckCircle2, AlertCircle } from "lucide-react";

export interface ApprovalTask {
  id: string;
  workflow_type: string;
  institution_id?: string;
  status?: string;
  payload: {
    student_name?: string;
    course_name?: string;
    recommended_grade?: string;
    recommended_feedback?: string;
    reason?: string;
    notice_title?: string;
  };
  created_at: string;
}

export const AIApprovalQueue: React.FC = () => {
  const [tasks, setTasks] = useState<ApprovalTask[]>([
    {
      id: "task-1",
      workflow_type: "grade_recommendation",
      payload: {
        student_name: "Alex Johnson",
        course_name: "CS101: Distributed AI Systems",
        recommended_grade: "A- (92%)",
        recommended_feedback: "Excellent analysis of spatial complexity. Minor omission in recursive base case.",
      },
      created_at: "10 mins ago",
    },
    {
      id: "task-2",
      workflow_type: "attendance_warning",
      payload: {
        student_name: "Sarah Miller",
        course_name: "AI201: Neural RAG & Vector DBs",
        reason: "Student missed 3 consecutive lectures. Recommended warning notification to academic advisor.",
      },
      created_at: "1 hour ago",
    },
    {
      id: "task-3",
      workflow_type: "official_notice",
      payload: {
        notice_title: "Campus AI Hackathon 2026",
        reason: "Autonomous event notification generated by AgentCampus AI Coordinator for student broadcast.",
      },
      created_at: "3 hours ago",
    },
  ]);

  const [filterType, setFilterType] = useState<string>("all");
  const [loading, setLoading] = useState<boolean>(false);
  const [notification, setNotification] = useState<{ message: string; type: "success" | "error" } | null>(null);

  const fetchPendingTasks = async () => {
    setLoading(true);
    try {
      const res = await fetch("http://localhost:8000/api/v1/ai-approval/queue", {
        headers: {
          "X-Institution-Id": "11111111-1111-1111-1111-111111111111",
        },
      });
      if (res.ok) {
        const data = await res.json();
        if (Array.isArray(data) && data.length > 0) {
          setTasks(data);
        }
      }
    } catch (err) {
      console.log("Using static fallback demo tasks.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPendingTasks();
  }, []);

  const handleAction = async (taskId: string, action: "approve" | "reject") => {
    try {
      const res = await fetch(`http://localhost:8000/api/v1/ai-approval/${taskId}/${action}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-User-Id": "22222222-2222-2222-2222-222222222222",
        },
      });
      
      setTasks((prev) => prev.filter((t) => t.id !== taskId));
      setNotification({
        message: `Task ${taskId} successfully ${action === "approve" ? "approved & committed" : "rejected"}.`,
        type: "success",
      });
    } catch (err) {
      setTasks((prev) => prev.filter((t) => t.id !== taskId));
      setNotification({
        message: `Task ${taskId} successfully ${action === "approve" ? "approved" : "rejected"} (Demo mode).`,
        type: "success",
      });
    }

    setTimeout(() => setNotification(null), 4000);
  };

  const filteredTasks = filterType === "all" ? tasks : tasks.filter((t) => t.workflow_type === filterType);

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b pb-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-amber-500/10 text-amber-600 border border-amber-500/20 flex items-center gap-1">
              <ShieldAlert className="h-3.5 w-3.5" /> Human-in-the-Loop Active
            </span>
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight flex items-center gap-2 mt-1">
            <Sparkles className="h-7 w-7 text-amber-500" />
            AI Workflow Approval Engine
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Review and validate autonomous AI recommendations before they are committed to institutional records.
          </p>
        </div>

        <button
          onClick={fetchPendingTasks}
          disabled={loading}
          className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl border bg-card hover:bg-muted text-xs font-bold shadow-sm transition-colors"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} /> Refresh Queue
        </button>
      </div>

      {/* Filter Chips */}
      <div className="flex flex-wrap items-center gap-2 text-xs font-semibold">
        <button
          onClick={() => setFilterType("all")}
          className={`px-3 py-1.5 rounded-lg border transition-all ${
            filterType === "all"
              ? "bg-primary text-primary-foreground border-primary shadow-sm"
              : "bg-card text-muted-foreground hover:bg-muted"
          }`}
        >
          All Tasks ({tasks.length})
        </button>
        <button
          onClick={() => setFilterType("grade_recommendation")}
          className={`px-3 py-1.5 rounded-lg border transition-all ${
            filterType === "grade_recommendation"
              ? "bg-primary text-primary-foreground border-primary shadow-sm"
              : "bg-card text-muted-foreground hover:bg-muted"
          }`}
        >
          Grade Recs ({tasks.filter((t) => t.workflow_type === "grade_recommendation").length})
        </button>
        <button
          onClick={() => setFilterType("attendance_warning")}
          className={`px-3 py-1.5 rounded-lg border transition-all ${
            filterType === "attendance_warning"
              ? "bg-primary text-primary-foreground border-primary shadow-sm"
              : "bg-card text-muted-foreground hover:bg-muted"
          }`}
        >
          Attendance Flags ({tasks.filter((t) => t.workflow_type === "attendance_warning").length})
        </button>
      </div>

      {/* Toast Notification */}
      {notification && (
        <div className="p-4 rounded-xl border bg-emerald-500/10 text-emerald-700 border-emerald-500/30 text-xs font-semibold flex items-center justify-between">
          <span className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4" /> {notification.message}
          </span>
          <button onClick={() => setNotification(null)} className="hover:opacity-80">
            <X className="h-4 w-4" />
          </button>
        </div>
      )}

      {/* Queue Task List */}
      {filteredTasks.length === 0 ? (
        <div className="p-16 text-center border rounded-2xl bg-card space-y-3 shadow-sm">
          <UserCheck className="h-12 w-12 text-emerald-500 mx-auto" />
          <h3 className="text-xl font-extrabold text-foreground">Queue Cleared!</h3>
          <p className="text-sm text-muted-foreground">
            All pending AI workflow recommendations have been reviewed and processed.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredTasks.map((task) => (
            <div
              key={task.id}
              className="p-6 rounded-2xl border bg-card shadow-sm hover:border-primary/50 transition-all space-y-4"
            >
              <div className="flex items-center justify-between border-b pb-3">
                <div className="flex items-center gap-2">
                  <span className="px-2.5 py-1 rounded-md text-[11px] font-extrabold uppercase bg-amber-500/10 text-amber-600 border border-amber-500/20">
                    {task.workflow_type.replace(/_/g, " ")}
                  </span>
                  <span className="text-xs text-muted-foreground">{task.created_at}</span>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleAction(task.id, "reject")}
                    className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl border border-red-500/30 bg-red-500/10 hover:bg-red-500/20 text-red-600 text-xs font-bold transition-all"
                  >
                    <X className="h-3.5 w-3.5" /> Reject
                  </button>
                  <button
                    onClick={() => handleAction(task.id, "approve")}
                    className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-md transition-all"
                  >
                    <Check className="h-3.5 w-3.5" /> Approve & Execute
                  </button>
                </div>
              </div>

              <div className="text-sm space-y-2">
                {task.payload.notice_title && (
                  <p>
                    <span className="font-bold text-foreground">Announcement Title:</span> {task.payload.notice_title}
                  </p>
                )}
                {task.payload.course_name && (
                  <p>
                    <span className="font-bold text-foreground">Course:</span> {task.payload.course_name}
                  </p>
                )}
                {task.payload.student_name && (
                  <p>
                    <span className="font-bold text-foreground">Student:</span> {task.payload.student_name}
                  </p>
                )}
                {task.payload.recommended_grade && (
                  <p>
                    <span className="font-bold text-foreground">Recommended Grade:</span>{" "}
                    <span className="font-bold text-emerald-600 dark:text-emerald-400">{task.payload.recommended_grade}</span>
                  </p>
                )}
                {task.payload.recommended_feedback && (
                  <p className="text-muted-foreground bg-muted/50 p-3.5 rounded-xl text-xs italic border">
                    "{task.payload.recommended_feedback}"
                  </p>
                )}
                {task.payload.reason && (
                  <p className="text-amber-700 dark:text-amber-300 text-xs bg-amber-500/10 p-3 rounded-xl border border-amber-500/20">
                    {task.payload.reason}
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default AIApprovalQueue;
